version: "3.9"

services:
  webserver:
    build:
      args:
        BUILD_ENV: 'prod'
  celery:
    build:
      args:
        BUILD_ENV: 'prod'
    volumes:
      - proact-cache:/proact/celery/cache
      - proact-uploaded:/proact/celery/data/uploaded
  fastapi:
    build:
      args:
        BUILD_ENV: 'prod'
    volumes:
      - proact-cache:/proact/fastapi/cache
      - proact-uploaded:/proact/fastapi/data/uploaded

volumes:
  proact-cache:
  proact-uploaded:
