version: "3.9"

services:
  webserver:
    build:
      args:
        BUILD_ENV: 'dev'
    volumes:
      - ./frontend:/proact/webserver
  celery:
    build:
      args:
        BUILD_ENV: 'dev'
    volumes:
      - ./backend:/proact/celery
  fastapi:
    build:
      args:
        BUILD_ENV: 'dev'
    volumes:
      - ./backend:/proact/fastapi
  redis:
    ports:
      - "6379:6379"
