version: '3'

services:
  postgrest-db:
    container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /data/postgres-db:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c", "listen_addresses=*", "-c", "log_statement=all"]